version: "3"
services:
  database:
    image: mongo:3.2.4
    container_name: "database"
    ports:
      - 27017:27017
    command: --smallfiles
  api:
    image: boot-flux
    ports:
      - 9091:8080
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    links:
      - database